modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hibernalherbs"
version = "${version}"
displayName = "Hibernal Herbs"
authors = "DakotaPride"
description = '''
[MMD Winterjam 2022] Wanna celebrate the holidays with a touch of mystical blends? Here you are!
'''
#logoFile = ""

[[dependencies.hibernalherbs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hibernalherbs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hibernalherbs]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
