# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21
loader_version=0.16.9

# Mod Properties
mod_version=1.4.1.1
maven_group=net.dakotapride.hibernalherbs
archives_base_name=hibernalherbs

# Dependencies
fabric_version=0.102.0

# JEI & REI
# https://www.curseforge.com/minecraft/mc-mods/jei/files
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files
# jei_version=19.8.2.99
# rei_version=16.0.762
# EMI
# https://www.curseforge.com/minecraft/mc-mods/emi/files
emi_version=1.1.12

# Trinkets & Curios
# https://www.curseforge.com/minecraft/mc-mods/trinkets/files
# https://www.curseforge.com/minecraft/mc-mods/curios/files
# trinkets_version=3.10.0
# curios_version=9.0.9+1.21
# Accessories
# https://www.curseforge.com/minecraft/mc-mods/accessories/files
accessories_version=1.0.0-beta.33

# Patchouli
# https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric/files
# This version will correspond to both Forge & Fabric versions
patchouli_version=1.21-87